<div class="container">
    <div class="row">
        <h1>O naší redakci</h1>
        <p class=lead style="text-align: justify;">Lorem ipsum dolor sit amet, 
            consectetuer adipiscing
            elit. Integer vulputate sem a nibh rutrum
            consequat. Praesent vitae arcu tempor neque
            lacinia pretium. Aliquam id dolor. Aliquam
            erat volutpat. Ut enim ad minima veniam,
            quis nostrum exercitationem ullam corporis 
            suscipit laboriosam, nisi ut aliquid ex ea 
            commodi consequatur? Nunc auctor. Nullam 
            feugiat, turpis at pulvinar vulputate, erat 
            libero tristique tellus, nec bibendum odio 
            risus sit amet ante. Nullam sit amet magna 
            in magna gravida vehicula. Mauris metus.</p>
        <img src="/vendor/img/justkitty.jpg"  class="onas-kitty rounded img-fluid float-end" alt="...">
    </div>
</div>